from generate_reports.config import CLIENT, AZURE_OPENAI_LLM_DEPLOYMENT
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type
import logging, json

logger = logging.getLogger(__name__)

@retry(
    stop=stop_after_attempt(4),
    wait=wait_exponential(multiplier=1.2, min=2, max=15),
    retry=retry_if_exception_type(Exception),  # adjust to more specific exceptions if desired
    reraise=True,           # let caller handle final failure if needed
    before_sleep=lambda retry_state: logger.warning(
        "LLM call failed (attempt %d/%d): %s",
        retry_state.attempt_number,
        retry_state.outcome.exception(),
    ),
)
def _call_llm(messages: list[dict[str, str]], max_tokens: int = 2500, temperature: float = 0.7) -> str:
    """Centralized LLM call with consistent parameters."""
    response = CLIENT.chat.completions.create(
        model=AZURE_OPENAI_LLM_DEPLOYMENT,
        messages=messages,
        max_completion_tokens=max_tokens,
        # reasoning_effort="minimal",   # ← not a real parameter in official OpenAI / Azure API
    )
    try:

        content = response.choices[0].message.content
        raw_text = content.strip().removeprefix("```json").removesuffix("```").strip()
        if not content:
            logger.warning('No valid response is generated by llm')
            return {}
        return json.loads(raw_text)
    except:
        print('_call_llm issue reported')
        return {}
    
